---
# tasks file for elastic
- hosts: elastic
  tasks:
    - name: Adicionado key
      become: true
      rpm_key:
        state: present
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    - name: Creando repo
      copy:
        dest: "/etc/yum.repos.d/elasticsearch.repo"
        content: |
            [elasticsearch-7.x]
            name=Elasticsearch repository for 7.x packages
            baseurl=https://artifacts.elastic.co/packages/7.x/yum
            gpgcheck=1
            gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
            enabled=1
            autorefresh=1
            type=rpm-md
    - name: Instalando el JDK
      package: 
       name: java-latest-openjdk-devel
       state: present
    - name: Instalando el elastic
      package: 
       name: elasticsearch
       state: present
    - name: Copiando configuracion
      become: true
      template:
        src: "elasticsearch.yml.j2"
        dest: "/etc/elasticsearch/elasticsearch.yml"
        owner: root
        group: root
        mode: '0644'
        backup: yes
    - name:  systemctl daemon-reload
      become: true
      shell: "/bin/systemctl daemon-reload"
      register: shell_output
    - debug: var=shell_output
    - name: systemctl enable elasticsearch.service
      become: true
      shell: "/bin/systemctl enable elasticsearch.service"
      register: service_salida
    - debug: var=service_salida 
      notify: restart_elasticsearch_services
    - name: Open port elasticsearch
      firewalld:
       service: elasticsearch
       permanent: true
       zone: dmz
       state: enabled
    - name: open ports tcp
      firewalld:
       port: 9200/tcp
       permanent: yes
       zone: dmz
       state: enabled
    - name: open udp
      firewalld:
       port: 9200/udp
       permanent: yes
       zone: dmz
       state: enabled
    - name: restartd firewalld
      service: 
        name: firewalld 
        state: restarted