---
# tasks file for elastic
- hosts: elastic
  tasks:
    - name: Adicionado repo
      become: true
      shell:
         "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"

    - name: Instalando el elastic
      package: 
       name: elasticsearch
       state: present
